server:
  port: 8080
spring:
  application:
    name: "crediya-autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: ${DB_PORT}
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    database: "${DB_DATABASE}"
    schema: "public"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"

paths:
  login: "${PATHS_LOGIN}"
  roles: "${PATHS_ROLES}"
  users: "${PATHS_USERS}"
  findUserByEmail: "${PATHS_FIND_USER_BY_EMAIL}"

security:
  jwt:
    secret: "${JWT_SECRET}"
    expiration: 3000
